#!/usr/bin/env python3
"""
gen_synth_proto.py — combine a random selection of fleetbench proto schemas
into a single synthetic ``benchmark.proto`` + matching ``runtime_lengths.json``.

Background: the verilator-bench pipeline originally fed the 6 HyperProtoBench
schemas through ``proto_to_accel.py``, producing 6 workload profiles. For an
ML model that must generalize to OOD schemas that's too few distinct shapes —
this script extends the workload catalog with fleetbench-derived synthetic
benches. Each synthetic bench bundles ``--n-messages`` top-level fleetbench
``Message<N>`` types into a single .proto so the existing serializer/
deserializer emission path sees them as one multi-message workload.

Output layout (for ``--out-root gen/synth``):

    gen/synth/
      bench6/
        benchmark.proto           # concatenated proto schemas
        runtime_lengths.json      # per-message field length observations
        manifest.json             # {bench_id, seed, chosen_messages, ...}
      bench7/ ...
      synth_manifest.csv          # one row per synthetic bench

Inputs:

    fleetbench/fleetbench/proto/Message<N>.proto      — schema sources
    fleetbench/fleetbench/proto/access_message<N>.cc  — runtime value sources
                                                        (parsed by fleetbench_runtime)

Typical usage:

    python3 gen_synth_proto.py \\
        --count 20 --n-messages 5 --seed 42 \\
        --start-id 6 \\
        --out-root gen/synth

``--start-id 6`` reserves bench0..bench5 for the HPB benches; synthetic ids
begin at ``bench6``. Downstream scripts (Makefile, feature extractor, sweep
driver) all key on the flat ``bench<N>`` namespace, so nothing else needs to
change.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import os
import random
import re
import sys
from concurrent.futures import ProcessPoolExecutor, as_completed
from dataclasses import dataclass
from itertools import combinations
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# Allow importing the sibling lynx/fleetbench_runtime extractor without
# requiring a PYTHONPATH override.
_THIS = Path(__file__).resolve()
_LYNX_ROOT = _THIS.parent.parent / "lynx"
sys.path.insert(0, str(_LYNX_ROOT))
import fleetbench_runtime  # noqa: E402


DEFAULT_PROTO_DIR = _LYNX_ROOT / "fleetbench" / "fleetbench" / "proto"
DEFAULT_START_ID = 6  # bench0..bench5 are HPB; synthetic ids start at 6
DEFAULT_N_MESSAGES = 5
DEFAULT_COUNT = 20

# Matches a top-level `message Message<N> { ... }` block (including its
# nested types) in a fleetbench Message<N>.proto. Must respect nested braces
# — regex alone won't do, so we brace-balance in _extract_message_block.
_TOP_LEVEL_MSG_RE = re.compile(r"^message\s+(Message\d+)\s*\{", re.MULTILINE)


def _extract_message_block(proto_text: str) -> str:
    """Extract the `message Message<N> { ... }` block from a proto file.

    Each fleetbench Message<N>.proto has exactly one top-level message. We
    locate its opening `message ... {` and brace-balance to the matching `}`.
    Strips trailing whitespace; caller joins blocks with blank lines.
    """
    m = _TOP_LEVEL_MSG_RE.search(proto_text)
    if not m:
        raise ValueError("No top-level `message Message<N>` found")
    open_idx = proto_text.find("{", m.end() - 1)
    depth = 0
    i = open_idx
    while i < len(proto_text):
        c = proto_text[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return proto_text[m.start():i + 1]
        i += 1
    raise ValueError("Unterminated `message` block")


_PROTO_PREAMBLE = """// AUTO-GENERATED by verilator-bench/gen_synth_proto.py. Do not edit by hand.
// Synthetic benchmark combining fleetbench Message<N>.proto schemas.
syntax = "proto2";
package fleetbench.proto;

"""


def build_combined_proto(
    message_ids: List[int],
    proto_dir: Path,
    block_cache: Optional[Dict[int, str]] = None,
) -> str:
    """Return the concatenated benchmark.proto text for the given message ids.

    ``block_cache`` memoizes the parsed ``message Message<N> { ... }`` block
    per id so callers that emit many benches don't re-read and re-parse the
    same .proto files. Pass ``None`` for the legacy uncached behavior.
    """
    blocks: List[str] = []
    for mid in message_ids:
        if block_cache is not None and mid in block_cache:
            blocks.append(block_cache[mid])
            continue
        src = proto_dir / f"Message{mid}.proto"
        if not src.is_file():
            raise FileNotFoundError(f"Missing proto: {src}")
        block = _extract_message_block(src.read_text())
        if block_cache is not None:
            block_cache[mid] = block
        blocks.append(block)
    return _PROTO_PREAMBLE + "\n\n".join(blocks) + "\n"


def _extract_for_messages_cached(
    proto_dir: Path,
    message_ids: List[int],
    cache: Dict[int, Dict[str, Dict[str, List[int]]]],
) -> Dict[str, Dict[str, List[int]]]:
    """Runtime-lengths extractor with per-``Message<id>`` memoization.

    ``fleetbench_runtime.extract_for_messages`` re-parses each access_message
    .cc every call. When generating ``count`` benches each .cc gets visited
    ``count * n_messages / |pool|`` times — duplicated work. This helper
    stores each per-file parse in ``cache`` and merges on demand. Same
    output semantics as the underlying extractor.
    """
    from collections import defaultdict
    merged: Dict[str, Dict[str, List[int]]] = defaultdict(lambda: defaultdict(list))
    for mid in message_ids:
        if mid not in cache:
            cc = proto_dir / f"access_message{mid}.cc"
            if not cc.is_file():
                raise FileNotFoundError(f"Expected access .cc at {cc}")
            cache[mid] = fleetbench_runtime.extract_from_access_cc(cc)
        for owner, fields in cache[mid].items():
            for fname, lengths in fields.items():
                merged[owner][fname].extend(lengths)
    return {owner: dict(fields) for owner, fields in merged.items()}


@dataclass
class SynthBench:
    bench_id: int
    seed: int
    message_ids: List[int]

    @property
    def name(self) -> str:
        return f"bench{self.bench_id}"


def choose_benches(
    count: int,
    n_messages: int,
    start_id: int,
    available_ids: List[int],
    seed: int,
) -> List[SynthBench]:
    """Pick ``count`` distinct ``n_messages``-sized subsets, deterministically.

    Approach: enumerate every C(|available|, n_messages) subset via
    ``itertools.combinations`` (cheap — 20C5 = 15,504; 30C5 = 142,506), then
    deterministically shuffle that list under the global ``seed`` and take the
    first ``count`` entries. This guarantees:

      - **No duplicate subsets** across the generated catalog: each bench is
        a distinct 5-tuple of fleetbench messages. Birthday-paradox collisions
        in the previous per-bench RNG approach (≈500 duplicates at count=4000
        out of 20C5=15504 possible subsets) are eliminated.
      - **Hard failure when exhausted**: if ``count`` exceeds the number of
        available subsets, we error loudly instead of silently producing
        duplicates.
      - **Stability under growth**: appending to the catalog (raising
        ``--count`` with the same seed) leaves earlier benches identical.
        Changing ``--seed`` or ``--available-ids`` reshuffles the mapping.

    Each bench's stored ``seed`` is derived from the global seed and its
    bench_id so downstream emitters that consume ``SynthBench.seed`` (e.g.
    ``proto_to_accel.py --seed``) get a distinct per-bench RNG.
    """
    pool_size = len(available_ids)
    total_subsets = math.comb(pool_size, n_messages)
    if count > total_subsets:
        raise ValueError(
            f"Cannot draw {count} distinct {n_messages}-subsets from a pool of "
            f"{pool_size} messages: only {total_subsets} unique subsets exist. "
            f"Reduce --count, lower --n-messages, or enlarge --available-ids."
        )

    # All C(pool_size, n_messages) subsets, each pre-sorted by
    # ``combinations`` (lexicographic). Deterministic shuffle under ``seed``
    # so two runs with the same (pool, seed) produce the same ordering, and
    # the first ``count`` entries after shuffle are the catalog.
    all_subsets: List[Tuple[int, ...]] = list(combinations(sorted(available_ids), n_messages))
    rng = random.Random(seed)
    rng.shuffle(all_subsets)

    out: List[SynthBench] = []
    for i in range(count):
        bench_id = start_id + i
        chosen = list(all_subsets[i])  # already sorted (combinations is lex-ordered)
        local_seed = seed * 1_000_003 + bench_id
        out.append(SynthBench(bench_id=bench_id, seed=local_seed, message_ids=chosen))
    return out


def emit_bench(
    bench: SynthBench,
    proto_dir: Path,
    out_root: Path,
    proto_block_cache: Dict[int, str],
    runtime_cache: Dict[int, Dict[str, Dict[str, List[int]]]],
) -> Dict[str, object]:
    """Write one synthetic bench's proto + runtime lengths + manifest.

    ``proto_block_cache`` / ``runtime_cache`` are shared-per-invocation and
    memoize the parsed Message<id>.proto blocks and access_message<id>.cc
    runtime lengths. Without them each source file gets re-parsed
    ``count * n_messages / |pool|`` times — 82% of generation runtime on a
    200-bench run. With them generation scales linearly in output bytes.

    Returns a manifest-row dict suitable for the CSV index.
    """
    bench_dir = out_root / bench.name
    bench_dir.mkdir(parents=True, exist_ok=True)

    proto_text = build_combined_proto(bench.message_ids, proto_dir, proto_block_cache)
    (bench_dir / "benchmark.proto").write_text(proto_text)

    runtime = _extract_for_messages_cached(proto_dir, bench.message_ids, runtime_cache)
    (bench_dir / "runtime_lengths.json").write_text(
        json.dumps(runtime, indent=2, sort_keys=True)
    )

    n_fields_with_lengths = sum(len(v) for v in runtime.values())
    n_observations = sum(len(lst) for fields in runtime.values() for lst in fields.values())

    per_bench_manifest = {
        "bench_id": bench.bench_id,
        "name": bench.name,
        "seed": bench.seed,
        "message_ids": bench.message_ids,
        "top_level_messages": [f"Message{mid}" for mid in bench.message_ids],
        "runtime_simple_messages": len(runtime),
        "runtime_fields_with_lengths": n_fields_with_lengths,
        "runtime_observations": n_observations,
    }
    (bench_dir / "manifest.json").write_text(json.dumps(per_bench_manifest, indent=2))
    return per_bench_manifest


def write_manifest_csv(rows: List[Dict[str, object]], out_root: Path) -> Path:
    """Write a summary CSV indexing every synthetic bench."""
    csv_path = out_root / "synth_manifest.csv"
    fieldnames = [
        "bench_id", "name", "seed", "top_level_messages",
        "runtime_simple_messages", "runtime_fields_with_lengths",
        "runtime_observations",
    ]
    with csv_path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            row_out = dict(row)
            # Keep message_ids off the CSV (redundant with top_level_messages)
            # and stringify the list field.
            row_out.pop("message_ids", None)
            row_out["top_level_messages"] = ",".join(row_out["top_level_messages"])
            writer.writerow(row_out)
    return csv_path


def _log_emit(i: int, total: int, bench_name: str, row: Dict[str, object]) -> None:
    msgs = ",".join(row["top_level_messages"])
    print(
        f"[{i}/{total}] {bench_name}: "
        f"messages=({msgs}) "
        f"fields_with_lengths={row['runtime_fields_with_lengths']}",
        file=sys.stderr,
    )


def _emit_benches_serial(
    benches: List[SynthBench],
    proto_dir: Path,
    out_root: Path,
    proto_block_cache: Dict[int, str],
    runtime_cache: Dict[int, Dict[str, Dict[str, List[int]]]],
) -> List[Dict[str, object]]:
    """Write every synth bench in one process. Ordered, easy to debug."""
    rows: List[Dict[str, object]] = []
    for i, b in enumerate(benches, start=1):
        row = emit_bench(b, proto_dir, out_root, proto_block_cache, runtime_cache)
        _log_emit(i, len(benches), b.name, row)
        rows.append(row)
    return rows


# Worker-side helper: ProcessPoolExecutor pickles each call's arguments, so
# we pack the two per-run caches and the target paths into a dataclass that
# the pool initializer stashes in a process-global — avoids pickling those
# dicts (~1 MB at default pool size) once per submitted bench.
_WORKER_CTX: Optional[Dict[str, object]] = None


def _worker_init(
    proto_dir: str,
    out_root: str,
    proto_block_cache: Dict[int, str],
    runtime_cache: Dict[int, Dict[str, Dict[str, List[int]]]],
) -> None:
    global _WORKER_CTX
    _WORKER_CTX = {
        "proto_dir": Path(proto_dir),
        "out_root": Path(out_root),
        "proto_block_cache": proto_block_cache,
        "runtime_cache": runtime_cache,
    }


def _worker_emit(bench: SynthBench) -> Dict[str, object]:
    assert _WORKER_CTX is not None, "_worker_init must run first"
    return emit_bench(
        bench,
        _WORKER_CTX["proto_dir"],        # type: ignore[arg-type]
        _WORKER_CTX["out_root"],         # type: ignore[arg-type]
        _WORKER_CTX["proto_block_cache"],  # type: ignore[arg-type]
        _WORKER_CTX["runtime_cache"],    # type: ignore[arg-type]
    )


def _emit_benches_parallel(
    benches: List[SynthBench],
    proto_dir: Path,
    out_root: Path,
    proto_block_cache: Dict[int, str],
    runtime_cache: Dict[int, Dict[str, Dict[str, List[int]]]],
    workers: int,
) -> List[Dict[str, object]]:
    """Write synth benches in parallel.

    Each worker gets a pre-parsed copy of the source caches via
    ``_worker_init`` (which runs once per worker, not once per bench), so
    workers only pay the JSON-serialize + write-file cost per bench. The
    returned rows are re-sorted by ``bench_id`` to keep the manifest CSV
    ordered regardless of task completion order.
    """
    with ProcessPoolExecutor(
        max_workers=workers,
        initializer=_worker_init,
        initargs=(str(proto_dir), str(out_root), proto_block_cache, runtime_cache),
    ) as pool:
        futures = {pool.submit(_worker_emit, b): b for b in benches}
        rows: List[Dict[str, object]] = []
        for i, fut in enumerate(as_completed(futures), start=1):
            b = futures[fut]
            row = fut.result()
            _log_emit(i, len(benches), b.name, row)
            rows.append(row)

    rows.sort(key=lambda r: r["bench_id"])
    return rows


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--proto-dir", type=Path, default=DEFAULT_PROTO_DIR,
                    help="Directory holding fleetbench Message<N>.proto + "
                         f"access_message<N>.cc (default: {DEFAULT_PROTO_DIR}).")
    ap.add_argument("--out-root", type=Path, required=True,
                    help="Output root; one subdir per synthetic bench.")
    ap.add_argument("--count", type=int, default=DEFAULT_COUNT,
                    help=f"Number of synthetic benches to generate (default: {DEFAULT_COUNT}).")
    ap.add_argument("--n-messages", type=int, default=DEFAULT_N_MESSAGES,
                    help=f"Messages per synthetic bench (default: {DEFAULT_N_MESSAGES}).")
    ap.add_argument("--start-id", type=int, default=DEFAULT_START_ID,
                    help=f"First synthetic bench id (default: {DEFAULT_START_ID}). "
                         "HPB benches occupy ids 0..5.")
    ap.add_argument("--seed", type=int, default=0,
                    help="Global RNG seed (combined with bench_id for per-bench seeds).")
    ap.add_argument("--available-ids", type=str,
                    help="Comma-separated fleetbench message ids to draw from "
                         "(default: every Message<N>.proto in --proto-dir).")
    ap.add_argument("--workers", type=int, default=max(1, (os.cpu_count() or 2) // 2),
                    help="Parallel worker processes for bench emission (default: "
                         "half of nproc). Pass 1 to generate serially (useful "
                         "for profiling or reproducing stdout order).")
    args = ap.parse_args()

    if args.available_ids:
        available = [int(x) for x in args.available_ids.split(",") if x.strip()]
    else:
        available = sorted(int(p.stem.replace("Message", ""))
                           for p in args.proto_dir.glob("Message*.proto"))
    if len(available) < args.n_messages:
        sys.exit(f"Need at least {args.n_messages} fleetbench messages; "
                 f"only {len(available)} available in {args.proto_dir}")

    benches = choose_benches(
        count=args.count,
        n_messages=args.n_messages,
        start_id=args.start_id,
        available_ids=available,
        seed=args.seed,
    )

    args.out_root.mkdir(parents=True, exist_ok=True)

    # Pre-parse each source file ONCE. The ``available`` pool is at most a
    # few dozen entries, but without pre-parsing each one gets re-parsed
    # ``count * n_messages / |pool|`` times — 82% of generation runtime on
    # a serial 200-bench run before caching. We do this in the parent so
    # every worker starts with a fully populated cache and only pays the
    # per-bench write cost.
    proto_block_cache: Dict[int, str] = {}
    runtime_cache: Dict[int, Dict[str, Dict[str, List[int]]]] = {}
    for mid in available:
        src = args.proto_dir / f"Message{mid}.proto"
        proto_block_cache[mid] = _extract_message_block(src.read_text())
        cc = args.proto_dir / f"access_message{mid}.cc"
        runtime_cache[mid] = fleetbench_runtime.extract_from_access_cc(cc)

    rows: List[Dict[str, object]]
    if args.workers == 1:
        rows = _emit_benches_serial(benches, args.proto_dir, args.out_root,
                                    proto_block_cache, runtime_cache)
    else:
        rows = _emit_benches_parallel(benches, args.proto_dir, args.out_root,
                                      proto_block_cache, runtime_cache,
                                      workers=args.workers)
    csv_path = write_manifest_csv(rows, args.out_root)

    print(f"Generated {len(rows)} synthetic benches under {args.out_root}", file=sys.stderr)
    print(f"Manifest index: {csv_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
